name: Build

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish
        run: mvn deploy -P release


#      - name: Set up Apache Maven Central
#        uses: actions/setup-java@v1
#        with: # running setup-java again overwrites the settings.xml
#          java-version: 1.8
#          server-id: maven # Value of the distributionManagement/repository/id field of the pom.xml
#          server-username: MAVEN_USERNAME # env variable for username in deploy
#          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
#
#      - name: Publish to Apache Maven Central
#        run: mvn deploy -P release-maven
#        env:
#          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
#          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
